### ISSUE TITLE
grpc-lb-client fails to run

### ISSUE THREAD

**Issue by tindli** [bsm/grpclb#14]
I am running the grpc-lb-consul and the grpc-lb-client cmds together with consul.

When the client executes the call to "Servers" at https://github.com/bsm/grpclb/blob/d3ea10b1268286f35161baa2e1b44897abed29b9/cmd/grpc-lb-client/main.go#L38
it cancels the connection and stops.

FATAL rpc error: code = Internal desc = rpc error: code = Unavailable desc = grpc: the connection is unavailable

I debugged the problem and found, that the call to "Load" in order to update the score
https://github.com/bsm/grpclb/blob/master/balancer/backend.go#L63
fails.

I am not sure why the grpc-lb-client does not work but I assume, that the new balancer
created at https://github.com/bsm/grpclb/blob/master/cmd/grpc-lb-consul/main.go#L41 considers load reporting if nil configuration is used (and thus default applied)?

How is this supposed to work?

**Comment by tindli** [comment]
I have more information to provide:

1. The problem above seems to happen only, when there is no service client running. As soon as one is started, the server list is read. I was under the impression, that an empty list is returned, when no service clients are running... not sure why the "connection is unavailable" error is shown above in such a case... - but I am happy if this is the intended behavior.

2. I tried to do some real scheduling by implementing https://github.com/bsm/grpclb/blob/master/example_test.go#L11
It works great, even with 2 services - the requests are handled in round robin fashion.
Nevertheless I found, that there are cases when the call to c.SayHello() fails because the
client is not ready to be used...

c := pb.NewGreeterClient(conn)
//time.Sleep(1 * time.Second)
r, err := c.SayHello(context.Background(), &pb.HelloRequest{Name: "world"})

If a delay between the 2 lines is active, everything works as expected.
It seems that the initial(?) handling of the load balanced connection takes some time before a client can be created/used... 

Shouldn't the  call to pb.NewGreeterClient() block, until the client is ready to be used...?

**Comment by dim** [comment]
>  I was under the impression, that an empty list is returned, when no service clients are running ...
The assumption is that at least one of the servers is up and running. If not, the LB-client behaves exactly like a normal client that tries to connect to a single instance that is down.

> It seems that the initial(?) handling of the load balanced connection takes some time before a client can be created/used...
Sorry, I don't quite understand what you mean. Are you sure it's the client? Is your service running at the time you initialise a new client? Can you document your exact steps?

**Comment by tindli** [comment]
I have the following topology:

[A]-----[consul]-----[grpc-lb-consul]
                                       |                 |
                          [grpc-server-1]     [grpc-server-2]

whereas: 
[A]... is basically ExampleNewResolver() within example_test_go
[consul]... the cosul server downloaded from the web
[grpc-lb-consul]... the main.go from grpc-lb-consul directory
[grpc-server]... the main.go from greeter_server directory from grpc-go (helloworld)

Start order:
1. [consul]
2 [grpc-lb-consul]
3. [grpc-server-1]
4. [grpc-server-2]
5. [A]

There seems to be a timing issue that causes the c.SayHello() call to crash,
because pb.NewGreeterClient(conn) has not yet set up everything thats required...
(pb.NewGreeterClient() it does not seem to block until the NewGreeterClient is ready).

The problem can be prevented, by adding a sleep statement after calling
pb.NewGreeterClient(conn)... I can reliably reproduce this behavior.

-------------------------------
Related to the topology above:
Is it true that [grpc-lb-consul] is only required for startup?
I can stop it after the start order and [A] still reliably figures out, if 
[grpc-server-1] or [grpc-server-2] is alive (or both)...

Do you recommend running [grpc-lb-consul] on its own server?
Because then HA setup is required to prevent a single point of failure for [grpc-lb-consul]...
What do you recommend?

I hope that the topology outlined above is correct...

**Comment by dim** [comment]
So not quite, `A` should never talk to consul directly, and no, you cannot remove the grpc-lb-consul after start-up. 

The grpc-lb process follows the guidelines described in https://grpc.io/blog/loadbalancing. The whole purpose of this library is act as a mediator between the service actors (clients/servers) and the service discovery. It uses consul by default (but it could use any other compatible backend) to discover the service nodes. It then periodically pings the servers to obtain load statistics. Clients, never talk to consul directly, but - instead - exclusively talk to the LB to obtain information about the available servers (ordered by load). They then pick the best (least busy) server to connect to. On connection issues, they will automatically failover to a different server. Equally, if a new server comes online, GRPC-LB will pick it up and include it into its list. 

So to get things going, you need to:

1. consul to be running
2. start your GRPC servers (wait until they are picked up by consul)
3. start grpc-lb-consul (keep it running!)
4. start your GRPC client
